version: "3"
services:
  nginx-web:
    image: nginx:alpine
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    restart: unless-stopped
    deploy:
      # mode: global
      placement:
        constraints:
          - node.role == manager
      replicas: 1
    ports:
      - "${IP:-0.0.0.0}:80:80"
      - "${IP:-0.0.0.0}:443:443"
    volumes:
      - ${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./data}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./data}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs:ro
      - ${NGINX_FILES_PATH:-./data}/htpasswd:/etc/nginx/htpasswd:ro
      # - conf:/etc/nginx/conf.d
      # - vhost:/etc/nginx/vhost.d
      # - html:/usr/share/nginx/html
      # - certs:/etc/nginx/certs:ro
    networks:
      - ${NETWORK:-webproxy}
    logging:
      options:
        max-size: ${NGINX_WEB_LOG_MAX_SIZE:-4m}
        max-file: ${NGINX_WEB_LOG_MAX_FILE:-10}

  nginx-gen:
    image: helder/docker-gen
    command: -notify "docker-label-sighup com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy" -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen
    restart: unless-stopped
    deploy:
      # mode: global
      placement:
        constraints:
          - node.role == manager
      replicas: 1
    volumes:
      - ${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./data}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./data}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs:ro
      - ${NGINX_FILES_PATH:-./data}/htpasswd:/etc/nginx/htpasswd:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      # - conf:/etc/nginx/conf.d
      # - vhost:/etc/nginx/vhost.d
      # - html:/usr/share/nginx/html
      # - certs:/etc/nginx/certs:ro
      # - /var/run/docker.sock:/tmp/docker.sock:ro
      # - /srv/nginx-proxy/docker-gen/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    networks:
      - ${NETWORK:-webproxy}
    logging:
      options:
        max-size: ${NGINX_WEB_LOG_MAX_SIZE:-4m}
        max-file: ${NGINX_WEB_LOG_MAX_FILE:-10}

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      - DEFAULT_EMAIL=youremail@example.com
    restart: unless-stopped
    deploy:
      # mode: global
      placement:
        constraints:
          - node.role == manager
      replicas: 1
    volumes:
      - ${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./data}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./data}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # - conf:/etc/nginx/conf.d
      # - vhost:/etc/nginx/vhost.d
      # - html:/usr/share/nginx/html
      # - certs:/etc/nginx/certs
      # - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - ${NETWORK:-webproxy}
    logging:
      options:
        max-size: ${NGINX_WEB_LOG_MAX_SIZE:-4m}
        max-file: ${NGINX_WEB_LOG_MAX_FILE:-10}

networks:
  webproxy:
    external:
      name: ${NETWORK:-webproxy}

# volumes:
#   conf:
#   vhost:
#   html:
#   certs:

# networks:
#   default:
#     external:
#       name: ${NETWORK:-webproxy}